name: Build Sonic 1 and 2 for multiple platforms
on:
  push:
    branches:
      - master
      - main
      - win-actions
      - psvita

jobs:
  v4-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup devenv
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/SDL2-2.0.14 SDL2
      - name: Download libogg
        run : |
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/ogg/libogg-1.3.4.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libogg-1.3.4 libogg
      - name: Build libogg
        run: |
          devenv /upgrade ./dependencies/windows/libogg/win32/VS2015/libogg.sln
          devenv ./dependencies/windows/libogg/win32/VS2015/libogg.sln /build "Release|Win32"
      - name: Download libvorbis
        run : |
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libvorbis-1.3.7 libvorbis
      - name: Build libvorbis
        run: |
          devenv /upgrade ./dependencies/windows/libvorbis/win32/VS2010/vorbis_static.sln
          devenv ./dependencies/windows/libvorbis/win32/VS2010/vorbis_static.sln /build "Release|Win32"       
      - name: Build RSDKv4
        run: |
          devenv Sonic12Decomp.sln /build "Release|x86"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/Win32/Release/*.dll ./artifacts 
          move ./build/Win32/Release/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: Sonic12-Windows 
          path: artifacts      
  sonic1-psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake
      - name: Build Sonic 1
        run: |
          cd Sonic1.Vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: Sonic1-vita
          path: Sonic1.Vita/Sonic1.vpk
          if-no-files-found: error
  sonic2-psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake
      - name: Build Sonic 2
        run: |
          cd Sonic2.Vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: sonic2-vita
          path: Sonic2.Vita/Sonic2.vpk
          if-no-files-found: error
