name: Build RSDKv4
on:
  push:
    branches:
      - master
      - main
      - win-actions
      - linux-actions
      - 1.2.0

jobs:
  v4-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download libogg and libvorbis for easier includes
        run : |
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/ogg/libogg-1.3.4.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libogg-1.3.4 libogg
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libvorbis-1.3.7 libvorbis
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/SDL2-2.0.14 SDL2
      - name: Run vcpkg
        run: |
          vcpkg install libogg:x86-windows-static libvorbis:x86-windows-static
          vcpkg integrate install
      - name: Build RSDKv4
        run: |
          msbuild Sonic12Decomp.sln /p:Configuration=Release /p:Platform=x86 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions.props"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/Win32/Release/*.dll ./artifacts 
          move ./build/Win32/Release/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: v4-windows 
          path: artifacts      
  v4-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download libogg and libvorbis for easier includes
        run : |
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/ogg/libogg-1.3.4.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libogg-1.3.4 libogg
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libvorbis-1.3.7 libvorbis
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/SDL2-2.0.14 SDL2
      - name: Run vcpkg
        run: |
          vcpkg install libogg:x64-windows-static libvorbis:x64-windows-static
          vcpkg integrate install
      - name: Build RSDKv4
        run: |
          msbuild Sonic12Decomp.sln /p:Configuration=Release /p:Platform=x64 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions_x64.props"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/x64/Release/*.dll ./artifacts 
          move ./build/x64/Release/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: v4-windows-x64 
          path: artifacts      
  v4-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libvorbis-dev libsdl2-dev
      - name: Build RSDKv4
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: v4-linux
          path: bin/sonic2013
